const { contextBridge, ipcRenderer, webFrame } = require("electron");

// @generated-start shared-constants
// This block is auto-generated by scripts/sync-preload-shared.mjs.
// Do not edit manually.
const IPC_CHANNELS = Object.freeze({
  "projectOpenFolder": "project:open-folder",
  "settingsRead": "settings:read",
  "settingsWrite": "settings:write",
  "settingsWatch": "settings:watch",
  "settingsUnwatch": "settings:unwatch",
  "settingsFileChanged": "settings:file-changed",
  "terminalStart": "terminal:start",
  "terminalInput": "terminal:input",
  "terminalResize": "terminal:resize",
  "terminalStop": "terminal:stop",
  "terminalData": "terminal:data",
  "terminalExit": "terminal:exit",
  "clipboardWriteText": "clipboard:write-text",
  "filesystemReadDirectory": "filesystem:read-directory",
  "filesystemReadFile": "filesystem:read-file",
  "filesystemDeletePath": "filesystem:delete-path",
  "gitStatus": "git:status",
  "gitFileDiff": "git:file-diff",
  "gitRevertFile": "git:revert-file",
  "gitRevertAll": "git:revert-all",
  "gitLog": "git:log",
  "gitCommitDetails": "git:commit-details",
  "gitChanged": "git:changed",
  "gitWatch": "git:watch",
  "gitUnwatch": "git:unwatch",
  "globalQuickKey": "global:quick-key",
  "shellOpenExternal": "shell:open-external"
});

const SETTINGS_DIRNAME = ".ide";
const quickKeyBindings = Object.freeze([
  {
    "id": "quick-1",
    "accelerator": "Ctrl+Alt+Shift+1",
    "input": "1",
    "label": "1",
    "icon": null,
    "gridIndex": 1
  },
  {
    "id": "quick-2",
    "accelerator": "Ctrl+Alt+Shift+2",
    "input": "2",
    "label": "2",
    "icon": null,
    "gridIndex": 2
  },
  {
    "id": "quick-3",
    "accelerator": "Ctrl+Alt+Shift+3",
    "input": "3",
    "label": "3",
    "icon": null,
    "gridIndex": 3
  },
  {
    "id": "quick-4",
    "accelerator": "Ctrl+Alt+Shift+4",
    "input": "4",
    "label": "4",
    "icon": null,
    "gridIndex": 4
  },
  {
    "id": "quick-up",
    "accelerator": "Ctrl+Alt+Shift+Up",
    "input": "\u001b[A",
    "label": "Up",
    "icon": "arrow-up",
    "gridIndex": 6
  },
  {
    "id": "quick-esc",
    "accelerator": "Ctrl+Alt+Shift+E",
    "input": "\u001b",
    "label": "Esc",
    "icon": null,
    "gridIndex": 8
  },
  {
    "id": "quick-left",
    "accelerator": "Ctrl+Alt+Shift+Left",
    "input": "\u001b[D",
    "label": "Left",
    "icon": "arrow-left",
    "gridIndex": 9
  },
  {
    "id": "quick-down",
    "accelerator": "Ctrl+Alt+Shift+Down",
    "input": "\u001b[B",
    "label": "Down",
    "icon": "arrow-down",
    "gridIndex": 10
  },
  {
    "id": "quick-right",
    "accelerator": "Ctrl+Alt+Shift+Right",
    "input": "\u001b[C",
    "label": "Right",
    "icon": "arrow-right",
    "gridIndex": 11
  },
  {
    "id": "quick-enter",
    "accelerator": "Ctrl+Alt+Shift+Enter",
    "input": "\r",
    "label": "Enter",
    "icon": "enter",
    "gridIndex": 12
  }
]);
// @generated-end shared-constants
const MIN_ZOOM_FACTOR = 0.25;
const MAX_ZOOM_FACTOR = 5;

function normalizeZoomFactor(value) {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return null;
  }

  return Math.min(Math.max(value, MIN_ZOOM_FACTOR), MAX_ZOOM_FACTOR);
}

const exposedQuickKeys = quickKeyBindings.map((binding) => ({
  id: binding.id,
  accelerator: binding.accelerator,
  input: binding.input,
  label: binding.label,
  icon: binding.icon,
  gridIndex: binding.gridIndex
}));

contextBridge.exposeInMainWorld("projectApi", {
  quickKeys: exposedQuickKeys,
  openFolder: () => ipcRenderer.invoke(IPC_CHANNELS.projectOpenFolder),
  settings: {
    directoryName: SETTINGS_DIRNAME,
    read: (projectPath, filename) =>
      ipcRenderer.invoke(IPC_CHANNELS.settingsRead, projectPath, filename),
    write: (projectPath, filename, content) =>
      ipcRenderer.invoke(IPC_CHANNELS.settingsWrite, projectPath, filename, content),
    watch: (projectPath, filename) =>
      ipcRenderer.invoke(IPC_CHANNELS.settingsWatch, projectPath, filename),
    unwatch: () => ipcRenderer.invoke(IPC_CHANNELS.settingsUnwatch),
    onFileChanged: (listener) => {
      const handler = (_event, filename) => listener(filename);
      ipcRenderer.on(IPC_CHANNELS.settingsFileChanged, handler);
      return () => ipcRenderer.removeListener(IPC_CHANNELS.settingsFileChanged, handler);
    }
  },
  terminal: {
    start: (cwd, size, sessionId) =>
      ipcRenderer.invoke(IPC_CHANNELS.terminalStart, cwd, size, sessionId),
    input: (data, sessionId) =>
      ipcRenderer.invoke(IPC_CHANNELS.terminalInput, data, sessionId),
    resize: (size, sessionId) =>
      ipcRenderer.invoke(IPC_CHANNELS.terminalResize, size, sessionId),
    stop: (sessionId) => ipcRenderer.invoke(IPC_CHANNELS.terminalStop, sessionId),
    onData: (listener) => {
      const handler = (_event, payload) => listener(payload.data, payload.sessionId);
      ipcRenderer.on(IPC_CHANNELS.terminalData, handler);
      return () => ipcRenderer.removeListener(IPC_CHANNELS.terminalData, handler);
    },
    onExit: (listener) => {
      const handler = (_event, payload) => listener(payload.code, payload.sessionId);
      ipcRenderer.on(IPC_CHANNELS.terminalExit, handler);
      return () => ipcRenderer.removeListener(IPC_CHANNELS.terminalExit, handler);
    }
  },
  clipboard: {
    writeText: (text) => ipcRenderer.invoke(IPC_CHANNELS.clipboardWriteText, text)
  },
  shell: {
    openExternal: (url) => ipcRenderer.invoke(IPC_CHANNELS.shellOpenExternal, url)
  },
  filesystem: {
    readDirectory: (dirPath) => ipcRenderer.invoke(IPC_CHANNELS.filesystemReadDirectory, dirPath),
    readFile: (projectPath, filePath) =>
      ipcRenderer.invoke(IPC_CHANNELS.filesystemReadFile, projectPath, filePath),
    deletePath: (projectPath, targetPath) =>
      ipcRenderer.invoke(IPC_CHANNELS.filesystemDeletePath, projectPath, targetPath)
  },
  git: {
    getStatus: (projectPath) => ipcRenderer.invoke(IPC_CHANNELS.gitStatus, projectPath),
    getFileDiff: (projectPath, filePath) =>
      ipcRenderer.invoke(IPC_CHANNELS.gitFileDiff, projectPath, filePath),
    revertFile: (projectPath, filePath) =>
      ipcRenderer.invoke(IPC_CHANNELS.gitRevertFile, projectPath, filePath),
    revertAll: (projectPath) => ipcRenderer.invoke(IPC_CHANNELS.gitRevertAll, projectPath),
    getLog: (projectPath, maxCount) =>
      ipcRenderer.invoke(IPC_CHANNELS.gitLog, projectPath, maxCount),
    getCommitDetails: (projectPath, hash) =>
      ipcRenderer.invoke(IPC_CHANNELS.gitCommitDetails, projectPath, hash),
    watch: (projectPath) => ipcRenderer.invoke(IPC_CHANNELS.gitWatch, projectPath),
    unwatch: () => ipcRenderer.invoke(IPC_CHANNELS.gitUnwatch),
    onChanged: (listener) => {
      const handler = () => listener();
      ipcRenderer.on(IPC_CHANNELS.gitChanged, handler);
      return () => ipcRenderer.removeListener(IPC_CHANNELS.gitChanged, handler);
    }
  },
  zoom: {
    getFactor: () => webFrame.getZoomFactor(),
    setFactor: (factor) => {
      const normalizedFactor = normalizeZoomFactor(factor);
      if (normalizedFactor === null) {
        return false;
      }

      webFrame.setZoomFactor(normalizedFactor);
      return true;
    }
  },
  onGlobalQuickKey: (listener) => {
    const handler = (_event, input) => listener(input);
    ipcRenderer.on(IPC_CHANNELS.globalQuickKey, handler);
    return () => ipcRenderer.removeListener(IPC_CHANNELS.globalQuickKey, handler);
  }
});
